// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9N4CTb-dUsJvAs44xTnnwEALpRsTKv24',
    appId: '1:755925064690:web:147eedf3b462164cc0296b',
    messagingSenderId: '755925064690',
    projectId: 'fruits-app-156c6',
    authDomain: 'fruits-app-156c6.firebaseapp.com',
    storageBucket: 'fruits-app-156c6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsbW1OP4dEsa9gR4H8GT4BfVdg9EguQ98',
    appId: '1:755925064690:android:0df58363ae2ba050c0296b',
    messagingSenderId: '755925064690',
    projectId: 'fruits-app-156c6',
    storageBucket: 'fruits-app-156c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOmRKr9iOU2nwVE8FrjkT2BIPQkJiGs44',
    appId: '1:755925064690:ios:31995b4e03a8186bc0296b',
    messagingSenderId: '755925064690',
    projectId: 'fruits-app-156c6',
    storageBucket: 'fruits-app-156c6.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOmRKr9iOU2nwVE8FrjkT2BIPQkJiGs44',
    appId: '1:755925064690:ios:31995b4e03a8186bc0296b',
    messagingSenderId: '755925064690',
    projectId: 'fruits-app-156c6',
    storageBucket: 'fruits-app-156c6.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9N4CTb-dUsJvAs44xTnnwEALpRsTKv24',
    appId: '1:755925064690:web:fdfa6d9fd76f44fcc0296b',
    messagingSenderId: '755925064690',
    projectId: 'fruits-app-156c6',
    authDomain: 'fruits-app-156c6.firebaseapp.com',
    storageBucket: 'fruits-app-156c6.firebasestorage.app',
  );
}
